;;; Emacs --- Functionality

;;; Commentary:
;;; Author: Eduardo Parducci
;;; Time-stamp: <2019-01-31 12:10:05>
;;;
;;; Installed packages:
;;; - flycheck
;;; - typescript-mode
;;; - web-mode (HTML and CSS)
;;; - sass-mode
;;; - json-mode
;;; - auto-complete


;;; Code:

;; add MELPA to Emacs (package manager)
(require 'package)
(add-to-list 'package-archives '("MELPA Stable" . "https://stable.melpa.org/packages/") t)
(package-initialize)

;; Generated by EMACS Package Manager
(custom-set-variables
;; '(display-time-day-and-date t)
;; '(display-time-format "%A,%e de %B %H:%M")
 '(flycheck-typescript-html-config "/usr/lib/node_modules/tidy-html5/package.json")
 '(package-selected-packages
   (quote
    (auto-complete json-mode sass-mode web-mode typescript-mode flycheck))))
(custom-set-faces
 '(font-lock-comment-face ((t (:foreground "cyan"))))
 '(font-lock-string-face ((t (:foreground "yellow"))))
 '(font-lock-keyword-face ((t (:foreground "brightcyan" :weight bold))))
 '(font-lock-builtin-face ((t (:foreground "brightblue"))))
 '(font-lock-type-face ((t (:foreground "brightgreen"))))
 '(font-lock-constant-face ((t (:foreground "brightyellow" :weight bold))))
 '(font-lock-function-name-face ((t (:foreground "brightblue" :weight bold))))
 '(font-lock-variable-name-face ((t (:foreground "brightmagenta" :weight bold))))
 )

;; Open HTML files in html-mode
(add-to-list 'auto-mode-alist '("\\.html\\'" . html-mode))

;; Auto-complete config & autostart
(ac-config-default)
(defvar ac-modes)
(add-to-list 'ac-modes 'html-mode)
(add-to-list 'ac-modes 'typescript-mode)
(add-to-list 'ac-modes 'web-mode)
(add-to-list 'ac-modes 'sass-mode)

;; Flycheck (spell-checker for code) enable globaly
(add-hook 'after-init-hook #'global-flycheck-mode)

;; Disable backup file
(setq make-backup-files nil)
(setq auto-save-default nil)

;; Navigate keys setup
(global-set-key (kbd "M-<up>") 'windmove-up)
(global-set-key (kbd "M-<down>") 'windmove-down)
(global-set-key (kbd "M-<left>") 'windmove-left)
(global-set-key (kbd "M-<right>") 'windmove-right)

;; Smooth Scrolling
(setq mouse-wheel-scroll-amount '(1 ((shift) . 1)))
(setq mouse-wheel-progressive-speed nil)
(setq mouse-wheel-follow-mouse 't)
(setq scroll-step 1)

;; Font setting
(set-face-attribute 'default t :font "Source Code Pro Medium-9")
(set-frame-font "Source Code Pro Medium-9" nil t)

;; Enable line numbers
(global-linum-mode)
(linum-mode t)

;; Kill default buffers
(defun startup-layout ()
  (interactive)
  (delete-other-windows)
  (setq-default message-log-max nil)
  (kill-buffer "*Messages*")
  (kill-buffer "*scratch*"))
(setq inhibit-startup-screen t)
(startup-layout)

;; Disable menu and scrolling bars
(tool-bar-mode -1)
(menu-bar-mode -1)
(scroll-bar-mode -1)
(fringe-mode -1)

;;; init.el ends here
